### PR TITLE
Updated README.md for feedback application

### PR DESCRIPTION
**Pull request by sahil-rathi**
Updated the feedback application page readme in reference to the issue #44

### CODE REVIEW

**Comment by manjunani** [comment]
hey buddy can u go through the code and list out the it's uses in the readme file i didn't intended to have my details on the readme

run the application, try it out and the update the readme buddy

**Comment by sahil-rathi** [comment]
The application was not starting so I thought that was what you meant.
Anyways I am working on it now.

**Comment by manjunani** [comment]
Sure Thanks @sahil-rathi

**Comment by sahil-rathi** [comment]
@manjunani I have updated readme according to the app and also fixed few bugs in the package.json file according to the issue #44 Can you now merge this please. Thank You

**Review by manjunani — APPROVED** [review]

**Pull request merged**
