### PR TITLE
Made the internet speed tester in python

### PR DESCRIPTION
**Pull request by Shreejan-35**
Hey I have built the internet speed tester in python. It can do :- 
1. Download test
2. Upload test
3. Ping

### CODE REVIEW

**Review by manjunani — APPROVED** [review]

**Comment by manjunani** [comment]
@Shreejan-35 , can you add a readme file as well in this folder that you had created

**Comment by Shreejan-35** [comment]
Ok I will add. That will take some time as I am outside. It will be a brief readme

**Comment by Shreejan-35** [comment]
You can merge now.

**Comment by Shreejan-35** [comment]
Later I will make readme

**Comment by Shreejan-35** [comment]
Hey your repo is excluded from hactober..

**Comment by manjunani** [comment]
Not sure to which repo you might be referring to kindly check once again// also do share me the image where you had seen that this repo has been excluded from hacktoberfest

**Comment by Shreejan-35** [comment]
Oh sorry I mistakenly comment here

**Comment by manjunani** [comment]
oh okay, can u add the readme file as well so that i can merge the PR

**Comment by manjunani** [comment]
yep take your time buddy

**Comment by Shreejan-35** [comment]
Uploaded README

**Review by manjunani — APPROVED** [review]

**Pull request merged**
