### PR TITLE
Added a Typing game made with HTML,CSS,JAVASCRIPT

### PR DESCRIPTION
**Pull request by saikatdgp2001**
made a beginner friendly Typing Game

### CODE REVIEW

**Comment by saikatdgp2001** [comment]
plz accept it with proper tags.

**Comment by manjunani** [comment]
Hey @saikatdgp2001  Although i had accepted the previous PR, these games looks awesome buddy, if possible can you upload some codes related to useful implementation to the users instead of the games and all.... and do raise an issue first while before raising the PR so that i can check whether the issue is valid or not and will assign the respective issue under the name so that you can work on it.

**Comment by saikatdgp2001** [comment]
Plz accept this i made

**Comment by saikatdgp2001** [comment]
Can you please reopen and accept my project.

**Comment by saikatdgp2001** [comment]
Hi ,
Can you please reopen and please merge it with your repository. So that
people can contribute to make it more user friendly .

SAIKAT DAS

**Pull request closed without merging**
